---
- hosts: devstack
  gather_facts: False
  vars:
    devstack_repo: git://github.com/openstack-dev/devstack.git
    branch: master
    offline: no
    reclone: no
    git_base: git://github.com
    devstack_branch: "{{branch}}"
  tasks:
    - name: git
      apt: pkg=git state=present

    - name: checkout devstack
      sudo: no
      git: repo={{devstack_repo}} dest=/home/vagrant/devstack version={{devstack_branch}}

    - name: localrc
      sudo: no
      template: src=localrc.basic dest=/home/vagrant/devstack/localrc

    - name: stack.sh
      sudo: no
      shell: /home/vagrant/devstack/stack.sh 2>&1 > /tmp/stack.sh.log
